### ISSUE TITLE
Play nicely with create-react-app

### ISSUE THREAD

**Issue by jdelight** [BrandwatchLtd/axiom#152]
As far as I understand - you can't currently import components from axiom into a create-react-app project. I'm not 100 sure what's needed to fix this but if someone could summarise the issue and maybe we could discuss what's needed to get them working nicely.

https://github.com/facebookincubator/create-react-app

**Comment by siggysamson** [comment]
@kamilio Might have some insights on this as he was using Axiom and create-react-app for a prototype recently. IIRC he was using a custom build of Axiom but I don't remember what exactly it was about. It might have been about the `__INCLUDE_CSS__` vars but that could be resolved by now.

**Comment by HHogg** [comment]
I've just taken a look at and tried out `create-react-app`, and in particular read through [this super lengthy discussion](https://github.com/facebookincubator/create-react-app/issues/78) around how to deal with CSS and preprocessing alternatives. 

From what I can tell, `create-react-app` is already using `postcss` 🙌, which is what Axiom uses since the [recent Sass removal changes](https://github.com/BrandwatchLtd/axiom/pull/131), but what it doesn't allow, is to point to a custom `postcss.config.js`. 

`create-react-app` looks like a great project to get up and running within a minute (about how long it just took me), avoiding the need to trawl through webpack documentation... but it is designed as a learning tool or to quickly get up and running to try something out. 

Axiom is setup and designed for our production applications, and inherently has extra requirements to help our workflow (like with CSS variables, CSS imports, CSS color functions etc...) without these, maintaining Axioms design would be much harder. Axiom has a pretty minimal `postcss` setup, which I've added this to the bottom.

I think an ideal solution would be for `create-react-app` to look at the root of the project for it's config files before heading to its defaults, but that probably is well out of what they're aiming to do. 

```js
// Required postcss.config.js
module.exports = {
  plugins: [
    require('postcss-import')(),
    require('postcss-cssnext')({
      features: {
        customProperties: {
          variables: require('bw-axiom/lib/materials/theme-light.json'),
        },
      },
    }),
  ],
};
```

**Comment by jdelight** [comment]
Thanks for taking the time to look into this @HHogg - that makes a lot of sense. I think it's perfectly acceptable to eject from CRA to be able to use Axiom components. 

However, I wonder if it's possible to have a distribution of Axiom that gives you styled components. Particularly useful if you're prototyping or have little need for changing the default look.

**Comment by kamilio** [comment]
I created custom build file and pushed it to my fork.

I needed to remove the require('*.scss') files with babel plugin https://github.com/wssgcg1213/babel-plugin-inline-replace-variables to use the React components.

**Comment by HHogg** [comment]
I've added #281 for the moment, it does require CRA to be ejected but while having to support preprocessing css custom properties for IE11 I can't see a way around it.
