### ISSUE TITLE
Thoughts / options on e2e testing with JavaScript

### ISSUE THREAD

**Issue by jdelight** [BrandwatchLtd/axiom#218]
Just a short list of some JavaScript tools we could use to run e2e tests on Axiom.
By e2e tests I mean something along the lines of:

 - spin up a page with the component to test
 - perform an action on the component (click, type etc...)
 - verify that the expected output happens (i.e. a visible UI change in response to an event)

It may be that we have a dedicated page in Axiom which just has all the components in the most common states. Then wire up some arbitrary events and actions (e.g. clicking on a button should add some text to the page somewhere which can be tested). 

There are a few tools that sit in this space:

**Cypress.io**
[cypress.io](https://www.cypress.io/) is probably the newest tool and very different to the traditional selenium/webdriver driven approach. Built on top of chai, mocha, sinon. It's also built as a native application.

**Nightmare.js** 
[Nightmare.js](http://www.nightmarejs.org/) has the most number of GH stars and seems very comprehensive - however the API and examples might be harder to understand at a glance.

**Nightwatch.js** 
[nightwatch.js](http://nightwatchjs.org/) another popular option - API perhaps simpler than nightmare.

**Comment by siggysamson** [comment]
I've used Nightwatch.js before and found it slightly annoying to work with. Unfortunately I don't recall the exact pain points any more :/
What's the status of Cypress.io? They are offering "Early Access" since quite a while but I haven't seen any updates. Maybe they are about to release? (At least they seem to be active on Twitter so I think that's a good thing?)

What about using [WebdriverIO](http://webdriver.io/)? We've recently started using it for 2 projects and didn't have any issues with it. It was easy to set up and write tests. (Although we don't have a huge amount of tests just yet)

**Comment by HHogg** [comment]
We looked at a lot of the options out there, and we found GoogleChromes/Puppeteer to be the latest greatest, nice API and stable. We originally went with Nightmare.js but encountered some issues that meant we had to do a quick port over. 

I'm going to close this issue for the moment, if/when we come to a point of definitely adding ATs to Axiom we can explore the scene at that point in time (as it would have probably changed completely from this conversation).
