### ISSUE TITLE
Grid, what is it good for?

### ISSUE THREAD

**Issue by lpoulter** [BrandwatchLtd/axiom#589]
The Grid component has been a source of some confusion and frustration for myself and as such I've avoided using it. I've raised this issue to either get re-educated as to it's value or start the discussion to remove it.

The Grid greatly increases the mark up of a component that uses it. When using it I feel like I'm having to re-learn a less expressive form of CSS. `display: grid;` and `display: flex;` give you all the tools you need to create simple, powerful and expressive markup making the Grid somewhat redundant.

@jdelight has made some good comments on the issue here
https://github.com/BrandwatchLtd/axiom/pull/581#issuecomment-396320729

**Comment by antiBaconMachine** [comment]
It's been quite a while now since I've written anything using Axiom, but I was similarly confused and frustrated by this component last year. I remember having a conversation with @HHogg about it and badly paraphrasing he said something along the lines of 

> I wish I had called this 'flexHelper'

That alone helped me a bit at the time and it's what I have repeated when anyone else has asked me about Grid. As a starting point renaming it might help explain the purpose a bit better?

I also agree with the more radical position that it would be nice to style things using css, particualrly in this case. Learning flexbox is basically an essential tool for front-end dev in 2018 so I don't see why we couldn't use it.

**Comment by Binarytales** [comment]
I agree with the comments James made in the other PR. 

> I feel like I'm having to re-learn a less expressive form of CSS

I understand this sentiment a lot. The <Grid> component is a leaky abstraction. I think it's important to remember the [rule of least power](https://en.wikipedia.org/wiki/Rule_of_least_power) - which actually in this case is a bit inverted because while CSS is the less power language it is more expressive.

I vote for removing Grid from Axiom - or at least making it optional.

I can see a use case for a set of help _classes_ that can be applied to quickly create something that conforms to a standard base along the lines of [Bootstrap Grid](https://getbootstrap.com/docs/4.0/layout/grid/)

**Comment by HHogg** [comment]
I agree, the Gird component is pretty rubbish (I can say it so bluntly as I'm wrote it). 

The idea was to have a quick flex layout component for the so many common responsive flex layouts of "I want this to the left and to take up all the room, and this thing to the right and only be as big as it's contents". It was also the plan to add a friendly naming to the common layout types like "shrink" this thing.... but it totally got out of hand with more and more scenarios and variations of grow/shrink/basis. 

@TomWija create a POC for a display: grid <Grid> component and we've had plans for a while to create a low level Flex component that isn't an abstraction of the CSS terminology but just saves you writing the same CSS over and over again. 

Something like ... 

```jsx
<Flex direction="column"> { */ adds display flex */ }
  <Flex grow shrink>Some content</Flex>
  <Flex>Some other content</Flex>
</Flex>
```

Also the plan was to ditch the responsive values and have a `<Responsive>` component that uses the `matchMedia` API so you can have completely control over every single React prop and not just a few of the CSS based ones. 

.... but it's just time to work on these improvements.

**Comment by HHogg** [comment]
Just as an example for the ideas around [Flex](https://preshape.hogg.io/components/flex) and [Responsive](https://preshape.hogg.io/components/responsive/).

**Comment by lpoulter** [comment]
Thanks for the comments everyone. @HHogg Thanks for the background I think a `<Flex />` component would be slightly better. However I still think i'd rather just use css to give me more expression, future proofing and to make the JSX more semantic.

**Comment by siggysamson** [comment]
Isn't the benefit of a common `Flex`/`Grid`/whatever comment that it's going to _enforce_ the same layout across apps/pages?
By _just allowing CSS_ you create the risk of everyone doing something differently and also always doing it over and over again. I don't think we all are ending up writing the craziest layouts every day that require a lot of customization.
You **can** still write your own flexbox/grid layout by using the `Base` component with CSS classes, right?

I guess the problem with grid/flexbox in that particular case comes from the fact that some elements _just don't behave_ like a grid/flexbox container whereas it would be absolutely fantastic if you could make them do so.

I might understanding this wrongly but is it correct that there are essentially 2 different scenarios that we are looking after?

**Comment by HHogg** [comment]
I agree @siggysamson. Sorry to link again to Preshape ... but this is where I'm in favour of a [composable APIs](https://preshape.hogg.io/guides/composition).

```jsx
<DialogBody Component={ Flex }>
 ...
</DialogBody>
```

Essentially adding the behaviour of Flex to any other component.

**Comment by jdelight** [comment]
```jsx
<DialogBody Component={ Flex }>
```
I think it's personal choice :) a lot of people will prefer to just write:

```css
.my-dialog { 
    display: flex;
}
```
```jsx
<DialogBody classNames="my-dialog">
```
Because it's simple to understand and fits the way people have generally been working and using HTML/CSS.

I don't think there's much value in enforcing abstractions or specific idioms on everyone... that's the benefit of PRs and code review - to catch bad code (not limit expressivity).

Also people are quite happy writing CSS over and over again - it's just part of building user interfaces...

Seems like we're taking away the native solution and replacing it with a more awkward set of abstractions & a series of things to learn that are not as intuitive. 

I've still not seen any good arguments against CSS class names... :) but I'm very open to hear more and discuss them.

**Comment by ahume** [comment]
Closing in favour of epic AX-15.
